# Kubernetes 中 PersistentVolumeClaim 元件的版本號
apiVersion: v1

# 該元件的種類
kind: PersistentVolumeClaim

# 該元件的元資料
metadata:
  # 這個 PersistentVolumeClaim 的名稱
  name: {{ .Values.pvc.metadata.name }}
  namespace: {{ .Values.namespace.metadata.name }}

# 這個 PersistentVolumeClaim 的 PersistentVolumeClaimSpec
spec:
  # 要求的儲存空間大小
  resources:
    requests:
      storage: {{ .Values.pvc.spec.resources.requests.storage }}

  # 要求的儲存空間的卷模式
  volumeMode: {{ .Values.pvc.spec.volumeMode }}

  # 要求的儲存空間的存取模式
  accessModes: {{ .Values.pvc.spec.accessModes }}

  # 要求的儲存空間的儲存類型
  storageClassName: {{ .Values.pvc.spec.storageClassName }}
