# Kubernetes 中 Service 元件的版本號
apiVersion: v1

# 該元件的種類
kind: Service

# 該元件的元資料
metadata:
  # 這個 Service 的名稱
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.namespace.metadata.name }}

# 這個 Service 的 ServiceSpec
spec:
  # Service 要以哪種模式運作
  # Kubernetes 提供 ClusterIP、NodePort、ExternalName、LoadBalancer
  # 預設為 ClusterIP
  type: {{ .Values.service.spec.type }}

  # 要選取的 Pod
  selector:
    app: {{ .Values.pod.metadata.labels.app }}

  # 設定 Service 要連接的相關 port 號
  ports:
    - name: {{ .Values.pod.spec.containers.name}}

      # 決定要以哪種網路協議來進行連線，TCP、UDP、SCTP
      # 預設為 TCP
      protocol: {{ .Values.service.spec.ports.protocol }}

      # Service 要用哪個 port 號來連到 Pod
      # 通常 port 會跟 targetPort 設定為相同的 port 號
      port: {{ .Values.service.spec.ports.port }}

      # Pod 對外開放的 port 號
      # 沒設定 targetPort 的話，Kubernetes 預設會設為與 port 相同的 port 號
      targetPort: {{ .Values.service.spec.ports.targetPort }}

      # 指定外部連進 Service 的 port 號，範圍為 30000~32767
      # 沒設定 nodePort 的話，Kubernetes 會自動指派一個範圍內的 port 號作為 nodePort
      nodePort: {{ .Values.service.spec.ports.nodePort }}
